<?php

if (!defined('ABSPATH')) exit; // Exit if accessed directly

class Paykit_Gateway_Code_Enum
{
  const APPROVED = 'APPROVED';

  const SUB_MERCHANT_IS_REQUIRED = 'SUB_MERCHANT_IS_REQUIRED';

  const DUPLICATE_PAYMENT_ID = 'DUPLICATE_PAYMENT_ID';
  const DUPLICATE_REFUND_ID = 'DUPLICATE_REFUND_ID';

  const PAYMENT_NOT_FOUND = 'PAYMENT_NOT_FOUND';
  const REFUND_NOT_FOUND = 'REFUND_NOT_FOUND';

  const INVALID_PAYMENT = 'INVALID_PAYMENT';
  const INVALID_REFUND = 'INVALID_REFUND';
  const INVALID_AMOUNT = 'INVALID_AMOUNT';

  const PAYMENT_IS_BEING_REFUNDED = 'PAYMENT_IS_BEING_REFUNDED';
  const PAYMENT_IS_REFUNDED = 'PAYMENT_IS_REFUNDED';

  const AUTHENTICATION_NOT_SUPPORTED = 'AUTHENTICATION_NOT_SUPPORTED';
  const MERCHANT_NOT_SUPPORT_JCB = 'MERCHANT_NOT_SUPPORT_JCB';

  const INVALID_CARD_NUMBER = 'INVALID_CARD_NUMBER';
  const INVALID_EXPIRY = 'INVALID_EXPIRY';
  const INVALID_SECURITY_CODE = 'INVALID_SECURITY_CODE';
  const SECURITY_CODE_NOT_PROCESSED = 'SECURITY_CODE_NOT_PROCESSED';
  const DECLINED = 'DECLINED';
  const EXPIRED_CARD = 'EXPIRED_CARD';
  const INSUFFICIENT_FUNDS = 'INSUFFICIENT_FUNDS';
  const TIMED_OUT = 'TIMED_OUT';

  const CURRENCY_NOT_MATCH = 'CURRENCY_NOT_MATCH';
  const PAYMENT_METHOD_NOT_SUPPORTED = 'PAYMENT_METHOD_NOT_SUPPORTED';

  const EXCEEDED_RETRY_LIMIT = 'EXCEEDED_RETRY_LIMIT';
  const LOCK_FAILURE = 'LOCK_FAILURE';
  const BLOCKED = 'BLOCKED';

  const SERVER_FAILED = 'SERVER_FAILED';
  const PENDING = 'PENDING';
  const SYSTEM_ERROR = 'SYSTEM_ERROR';
  const UNKNOWN = 'UNKNOWN';
  const UNSPECIFIED_FAILURE = 'UNSPECIFIED_FAILURE';
}
